### ISSUE TITLE
Argo download all files option fails with "Secure Connection Failed"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2320] opened 2020-12-02 22:16 UTC
**Describe the bug**
The download all files option on an Argo show page fails with the following error (in Firefox, but Chrome also fails to download):

```
Secure Connection Failed

An error occurred during a connection to argo.stanford.edu. PR_CONNECT_RESET_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**User Impact**
It's not possible to download all files from an object with a single click.

**To Reproduce**
1. Go to an Argo item that has files, e.g. https://argo.stanford.edu/view/druid:bb003dn0409
2. Click on download all files (in the right hand side of the "contents" header)
3. Wait
4. Continue to wait
5. See error

**Expected behavior**
A zip should start downloading after a few seconds.

**Additional context**
Could this be the result of something changing after the UIT maintenance shut down? I just noticed the issue this week, but I don't use it that often so I don't remember when it last worked for me.

**Comment by justinlittman** [comment] 2020-12-09 14:01
After some testing, my best guess is that this is a networking issue between Argo and the user (not Argo and preservation). Will ask Ops to take a look.

**Comment by justinlittman** [comment] 2020-12-09 14:10
Interestingly, this works for QA, but not stage or production.

**Comment by jonrober** [comment] 2020-12-09 17:02
What is happening in the background when you click on that link?  Is argo trying to connect to another server for the content?  For instance, when I click on a specific file it gives the option of downloading from stacks.

**Comment by julianmorley** [comment] 2020-12-09 17:09
As I recall, doesn't this use the SDR API to download files? Is it possible to make a successful API call from the argo-prod boxes to wherever the API endpoint is?

**Comment by justinlittman** [comment] 2020-12-09 17:19
Yes, it is using the Preservation Client to retrieve files from preservation and returning them via a streaming zip.
https://github.com/sul-dlss/argo/blob/master/app/controllers/files_controller.rb#L75

We use the Preservation Client to retrieve them from preservation and return them via a stream (not zipped) without issue .
 https://github.com/sul-dlss/argo/blob/master/app/controllers/files_controller.rb#L47

Also, on production I've retrieved files using the Preservation Client via rails console without issue.

**Comment by jonrober** [comment] 2020-12-09 17:45
We were wondering what endpoint it connected to so that we could test that direct from one of the prod boxes, though it sounds like you've tested that via the rails console already.

How long does it take to retrieve the same files as in your example above, using the rails console?  Possibly we're hitting an apache timeout.

Nothing in the UIT change should have affected.  The change itself was to the network our vmware storage is on, not the network used to connect to a running machine.  And otherwise we didn't change anything in the software.  We might have given them more memory... we did to a handful of machines, but that's it on changes.

**Comment by justinlittman** [comment] 2020-12-09 18:38
Retrieving the files are super-fast. They're normal sized files. I'd be suspicious for a large number of files / large zip but it happens even with small number of files / small zip.

As @andrewjbtw noted, this may have been broken for some time. Andrew -- are we sure that this ever worked in stage/prod?

**Comment by julianmorley** [comment] 2020-12-09 18:39
If it's the same block of code it seems highly unlikely that it's a networking/VM issue causing it - if it were the firewall or a system setting, it would apply equally to both file retrieval methods.

**Comment by justinlittman** [comment] 2020-12-09 18:46
It's the same code for retrieving from preservation. However, it is different code for streaming back to the user. In the working case, it is a direct stream; in the non-working case, it is a zipped stream.

**Comment by andrewjbtw** [comment] 2020-12-09 18:54
This worked for months, at least up until sometime in November. I (and other users) have been able to use it to download up to about 15 GB. This was a new feature added this summer and would not have gone to prod if it hadn't worked.

From the user perspective, the way this worked was:

1. Click on the link
2. Wait a few seconds
3. Depending on your browser settings, either begin downloading or prompt for a location to save the file
4. Browser shows download progress

In the past when it failed, all of those steps would happen but the progress would end at some point - possibly a timeout or space issue.

**Comment by andrewjbtw** [comment] 2020-12-09 22:00
Not sure if anyone's made changes but this just worked for me with an object on stage:
https://argo-stage.stanford.edu/view/ry162sb3309

So it's now only prod where I'm not able to download.

**Comment by julianmorley** [comment] 2020-12-13 18:57
I'm almost certain this is some combination of code assumptions and blocked data paths. We'd need to know *exactly* what happens - the complete code path and implicated servers - from clicking the 'download' link in Argo to getting a zip made to the zip being transferred to the end user. My suspicion is that there's some javascript or Ruby somewhere that's trying to make a direct call from the client browser to maybe the sdr-api box(?), and that's being blocked by a firewall. But there's no way of knowing that without precise knowledge of what the code is doing, where it's doing it, and what it's trying to talk to.

**Comment by justinlittman** [comment] 2020-12-14 00:59
Sure @julianmorley. The code is https://github.com/sul-dlss/argo/blob/master/app/controllers/files_controller.rb#L68. This makes calls with Preservation Client to PresCat. The results are streamed into a zip which is streamed to the browser.

A few things to note:
* No javascript is involved.
* The browser communicates exclusively with Argo; it does not communicate with the sdr-api or any other service.
* The problem is only when zipping the files. Calls to https://github.com/sul-dlss/argo/blob/master/app/controllers/files_controller.rb#L36 that directly stream via Preservation Client (without zipping) work fine.
* Manually retrieving files via the Rails console work fine.
* This works in some environments but not others.

Happy to step through the code in more detail if it would help.

**Comment by vivnwong** [comment] 2021-01-05 19:19
@julianmorley did Justin commented give you better understanding of the code path and the characteristics of the symptoms? What will be helpful for Ops and Dev work together to resolve this issue?

**Comment by julianmorley** [comment] 2021-01-08 21:02
It really needs an architectural diagram or something similar that details the data flows between all the implicated components and servers (the 'and servers' bit is key). I suspect that this has something to do with the path the data takes to get between wherever it lies (prescat storage, presumably) and the client's browser, but I'm also not the right person to debug this, so I can only really suggest how I'd approach the problem.

**Comment by vivnwong** [comment] 2021-01-08 23:21
Ops will have more time to pair after Jan 25 regarding this issue.

**Comment by julianmorley** [comment] 2021-01-11 18:50
I had a quick poke at the various environments, and another question emerged:
- when the .zip file is created, is it written to disk anywhere prior to transfer to the client? (presumably yes?) 
I mention this because pres-qa-01 and pres-stage-01 have write access to the same /sdr-transfers and test storage root volumes, whereas in production preservation-catalog-prod-01 (which I *think* runs the pres api endpoint? Diagram detail) does not have write access to storage roots (by design) and does not mount the /sdr-transfers volume at all.

**Comment by jmartin-sul** [comment] 2021-01-11 20:00
> I had a quick poke at the various environments, and another question emerged:
> 
>     * when the .zip file is created, is it written to disk anywhere prior to transfer to the client? (presumably yes?)
>       I mention this because pres-qa-01 and pres-stage-01 have write access to the same /sdr-transfers and test storage root volumes, whereas in production preservation-catalog-prod-01 (which I _think_ runs the pres api endpoint? Diagram detail) does not have write access to storage roots (by design) and does not mount the /sdr-transfers volume at all.

@mjgiarlo can probably answer this more definitively than i, since i believe he was the one to implement this.  but as far as i know, the zip is constructed and stored entirely in memory and streamed to the client, and so shouldn't be written explicitly to disk.  i think this is the most relevant part of the code change?  https://github.com/sul-dlss/argo/pull/2066/files#diff-e59d7caeea87ea9d3b90569167e9f02bc0916b316b737d6c2c17e45d463d6925R55-R75

to the best of my knowledge, the /sdr-transfers space should only be used for pres cat's zip creation, which should only happen for creating cloud archives (and yes, that should only happen on the pres cat worker boxes, -02 through -04 on prod).  i believe the zip creation here is done entirely on the argo side, as pres cat streams the content to argo.

**Comment by jmartin-sul** [comment] 2021-01-11 20:10
at any rate, per the linked snippet, it seems to me that any temp storage of zip files or zip file chunks would be on the argo side, since pres cat is just sending unzipped files over to argo.

**Comment by jcoyne** [comment] 2021-01-11 20:45
There is no storage of zipfiles, it generates streaming zips.

**Comment by jermnelson** [comment] 2021-02-01 16:22
Testing from January 28th and 29th around the `download` method. The code is in the `t2320-debug` branch, basically the logging stops at line 77 before the call to Prescat Client. The network call made by the client is accepted and returned from preservation catalog but the client did not log the error in the **proc** on line 81. 

https://github.com/sul-dlss/argo/commit/602eea0b33737e3a41ed598ed3264f0ab84d5942#diff-e59d7caeea87ea9d3b90569167e9f02bc0916b316b737d6c2c17e45d463d6925L77-L83

**Comment by ndushay** [comment] 2021-02-02 19:30
(Notes from infra dev mtg):

Note: there is no code difference -- we deploy the same code.

- Oddity:  it works in stage, but not in production.   (may point to a difference on the ops end)
    - Kam and Jeremy worked on this together for a while and didn't find the problem.
- Oddity:  the size of the files / object doesn't seem to matter (e.g. fails on object < 2M)

Vivian:  devs should pair with Ops to figure this out.

Hints:
- looking at puppet between prescat, argo for stage and prod -- passenger differences?  Other puppet differences.
- looking at network topology for stage and prod
    - prescat can talk to argo but it still fails -- Jeremy and Kam looked specifically at this

**Comment by aaron-collier** [comment] 2021-02-02 23:26
Notes from investigation:

- I can communicate/access the file from pres_cat via argo:

```
filename = '92170065.pdf'
druid = 'druid:bb003dn0409'
version = 1
Preservation::Client.objects.content(druid: druid, filepath: filename, version: version)
```

results in a big dump of binary data... and a 200 response.

**Comment by kamchan** [comment] 2021-02-02 23:36
passenger version is 6.0.4 on stage and prod is 6.0.5 on preservation-catalog-prod-01.  All argo prod/stage nodes are on passenger 6.0.4.   puppet installs the latest at the time server is built.   http/https are opened between argo and pres <-> in both stage prod cases.  It doesn't look like it goes thru any other ports.  Since single file downloads work, I would not think it's a port being blocked issue unless ziptrick does something additional/otherwise.

**Comment by justinlittman** [comment] 2021-02-03 12:15
Also, you must be connected to VPN to reach argo stage, but do not need to be connected to VPN to reach argo prod suggesting another networking difference.

**Comment by jcoyne** [comment] 2021-02-03 14:55
Since Aaron was able to demonstrate the streaming download to Argo, that points to the trouble being on the argo-prod machine.

**Comment by kamchan** [comment] 2021-02-03 18:41
with the VPN thing, I did see puppet iptables set more restrictively on stage compared to prod, but then since it works on stage and not prod, I didn't think a less restrictive iptables on prod would be a reason why it doesn't work.

**Closed** 2021-02-03 23:30 UTC
Labels: bug
