### ISSUE TITLE
Write new custom tags facets for most used tags

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/argo#2305] opened 2020-11-03 18:43 UTC
**Describe the bug**

The home page is slow to load with many tags in the facet.  However, this facet is used quite often and setting a limit on the number of tags shown means many users will repeatedly have to click more.

We can identify common types of tags and create new facets for them by writing custom solr queries (like this: https://github.com/sul-dlss/argo/blob/master/app/controllers/catalog_controller.rb#L97-L117)

Most important tag types to have in their own facet:

- Project
- Registered By
- Process

Also see #2304 to reduce the limit on tags shown

**User Impact**

Users have to wait a long time to load the home page or click "more" if the number of tags shown is limited.

**Comment by andrewjbtw** [comment] 2020-11-03 20:35
I'm not sure how many tags we can put in a new facet before reproducing the problem, but other tags that are actively used:

- DPG (Goobi instructions are carried with certain DPG tags)
- ETD (potentially, not sure if this is favored over faceting on the APO)
- SMPL (potentially)

**Comment by vivnwong** [comment] 2020-11-20 17:34
If we have to do this work, Andrew needs more time to define what are the most used tags. We should approach this in a regular WC.

**Comment by jcoyne** [comment] 2021-12-09 16:23
Closed this because we implemented the lazy loading tags facet.

**Closed by jcoyne** 2021-12-09 16:23 UTC
Labels: enhancement, Hold for SH
