### ISSUE TITLE
Allow users with APO roles access to the APO itself

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#76] opened 2015-11-01 22:30 UTC
A person with any role in an APO should have access to view the APO. 

A person with a dor-apo-manager role in an APO should be able to edit the APO object itself as well as create a collection that is governed by that APO. 

Example Jon Manton in the ARS APO https://argo.stanford.edu/catalog/druid:bz845pv2292

**Comment by blalbrit** [comment] 2015-11-11 22:24
pending conversation with @eefahy

**Comment by mejackreed** [comment] 2015-12-17 21:45
Still pending?

**Comment by blalbrit** [comment] 2015-12-17 23:02
@LynnMcRae - where are we with this?

**Comment by LynnMcRae** [comment] 2015-12-17 23:26
I know of nothing blocking this unless there are more questions about what it means.  What was the conversation with Erin about? ... I don't see how that relates.

**Comment by blalbrit** [comment] 2015-12-17 23:52
I think that was the conversation about workgroups vs. ldap, wasn't it?

**Comment by LynnMcRae** [comment] 2016-01-06 19:29
I don't think this has anything to do with workgroup/ldap ...  An APO manager can get at any item governed by the APO but not the APO itself, which is an odd omission.  I’m hoping it’s as simple as augmenting the background filter that is constructed on roles to be  “objects governed by [list of my APOs] OR objects = [list of my APOs]", but I may be wrong about the mechanisms at play.

**Comment by darrenleeweber** [comment] 2016-01-06 21:44
@LynnMcRae - what is wrong with https://argo.stanford.edu/catalog/druid:bz845pv2292 ?  It displays fine.  What is the display or the interaction(s) that cause problems for this druid?

**Comment by LynnMcRae** [comment] 2016-01-06 22:03
A DEV test case ...

the Jarndyce Single-Volume Nineteenth-Century Novel Collection has one item, one collection object, and one APO ...

you can see all three with your super powers, but impersonate user llam813 (enter sunetid:llam813)and you can see the item and colleciton only. the APO disappears from your view.

**Comment by darrenleeweber** [comment] 2016-01-06 23:12
- "A person with a dor-apo-manager role in an APO should be able to edit the APO object itself as well as create a collection that is governed by that APO."  This seems to be controlled by logic that displays the UI buttons at:
  - https://github.com/sul-dlss/argo/blob/develop/app/helpers/argo_helper.rb#L130-L164

**Comment by darrenleeweber** [comment] 2016-01-07 18:11
The logic patterns uses in controllers and views are:
```
app/controllers/items_controller.rb
619:    if current_user.is_admin || @object.can_manage_content?(current_user.roles @apo)
625:    if current_user.is_admin || @object.can_view_content?(current_user.roles @apo)

app/controllers/apo_controller.rb
316:    if current_user.is_admin || @object.can_manage_content?(current_user.roles params[:id])

app/views/catalog/_show_sections/_default_contents.html.erb
21:          can_manage = current_user.is_admin || current_user.is_manager || (apo_pid && object.can_manage_content?(current_user.roles(apo_pid)))
22:          can_view = current_user.is_admin || current_user.is_manager || (apo_pid && object.can_view_content?(current_user.roles(apo_pid)))

app/helpers/argo_helper.rb
131:    if (object.datastreams.include? 'roleMetadata') && (current_user.is_admin || current_user.is_manager || object.can_manage_item?(current_user.roles(apo_pid)))
135:    if object.can_manage_item?(current_user.roles(apo_pid)) || current_user.is_admin || current_user.is_manager
```

**Comment by darrenleeweber** [comment] 2016-01-07 23:46
My crumbs from pairing with John today, to simulate the problem:

RE: https://github.com/sul-dlss/argo/blob/develop/app/models/user.rb#L30-L54
```
$ bundle exec rails c
> apo = Dor.find('druid:hv992ry2431')
> apo_solrdoc = Dor::SearchService.query('id:"' + apo.pid + '"')['response']['docs'].first
> apo_role_keys = apo_solrdoc.keys.select {|k| k.include? 'role'}
> apo_access_groups = apo_role_keys.map {|k| apo_solrdoc[k] }.flatten.uniq
> apo.roles
=> {"dor-apo-manager"=>
  ["workgroup:dlss:dor-viewer",
   "workgroup:dlss:developers",
   "workgroup:sdr:metadata-staff",
   "workgroup:dlss:pmag-staff",
   "workgroup:dlss:production-coordinators",
   "workgroup:sdr:spec-staff",
   "workgroup:dlss:dor-manager"]}

> u = User.find_or_create_by_remoteuser 'a_sunet_id'
> u.set_groups_to_impersonate ["workgroup:dlss:dor-manager"]
> u.groups
=> ["workgroup:dlss:dor-manager"]
> u.roles(apo.pid)
=> []
```

**Comment by darrenleeweber** [comment] 2016-01-12 00:30
Need to review the requirements on who can create and view APOs, per
https://github.com/sul-dlss/argo/blob/develop/config/initializers/permissions.rb

**Comment by darrenleeweber** [comment] 2016-01-12 01:54
@suntzu suggests this requires a full security audit of Argo to review the user groups and permissions and this could be beyond the focus for this bug.  In checking some specs today, there are no limitations on creating or viewing an APO based on role, in the app controllers.  What could be limited is the presentation of “argo control buttons” in the UI for the object displayed.  Is the focus of this bug only the display of these buttons?

**Comment by darrenleeweber** [comment] 2016-01-12 02:04
@lynnmcrea says, 'I don’t understand your statement "In checking some specs today, there are no limitations on creating or viewing an APO based on role.”    Initial access  to APOs for read or write is the same as for any object … you have to have a role in a governing APO to access items governed by that APO.  This is the rule we are extending, since that rule does not give you any access to the APO itself in which you have that role.  Once you have access, the view vs manager distinction determines whether you can take any actions or not per the tables on the consul page. The action in question for the APO is editing the APO (via the Edit APO blue button) which is what contains to the ability to manage roles and create collections.'

**Comment by LynnMcRae** [comment] 2016-01-12 02:29
The net of this fix would be these changes in the UI. Note that there are no changes to those of us in the SDR level roles, like sdr-administrator, since we can see and act on anything outside the APO role-enforced permissions.

- Today if a non-admin user opens the Object Type facet, they see their items and collections represented, but no APOs. Instead they should see something like we see below, but only including the APOs they have roles in.

![screen shot 2016-01-11 at 6 08 35 pm](https://cloud.githubusercontent.com/assets/1824732/12252725/ab1fd1b2-b88e-11e5-99d5-aca029a87157.png)
- This means that they can get to the APO via keyword searching
- This means that they can get to the APO directly with a URL like https://argo-stage-b.stanford.edu/catalog/druid:bm077td6448, or get to that APO by following the Admin Policy link from one of its items (which is really the same thing).

The final change is based on the difference between viewer and manager roles:
- Once on the detail page of an APO, the Edit APO button would be enabled only of the user had sdr-administrator or dor-apo-manager role access (and in theory the currently unimplemented sdr-manager role, should you find references to that in the code)

**Comment by darrenleeweber** [comment] 2016-01-12 04:49
Maybe the source of the issue lies in the DOR object method:
```
def can_view_metadata?(roles)
  intersect roles, groups_which_view_metadata
end
```

For example,
```
[11] pry(#<RSpec::ExampleGroups::Apo::WithViewingUser>)> dorObj.groups_which_view_metadata
=> ["dor-administrator", "sdr-administrator", "dor-apo-manager", "dor-apo-depositor", "dor-viewer", "sdr-viewer"]
[12] pry(#<RSpec::ExampleGroups::Apo::WithViewingUser>)> dorObj.roles
=> {"dor-apo-manager"=>["workgroup:dlss:developers"], "dor-apo-viewer"=>["person:sunetid:someone"]}
```
For this DOR APO object, the set of possible roles does not include 'dor-viewer' and so the APO cannot be view-only.  That is, the DOR object has a set of `groups_which_view_metadata` and a set of `roles`.  If the `dor-apo-viewer` role is matched for a user (based on the user workgroups), it doesn’t allow viewing the APO because there is no `dor-apo-viewer` in the `groups_which_view_metadata`.

So, for the APO `dorObj.groups_which_view_metadata`, should there be a `dor-apo-viewer`  in that set?  (If so, where is that set populated?)

**Comment by darrenleeweber** [comment] 2016-01-13 00:26
Concern above may be related to #203

**Comment by LynnMcRae** [comment] 2016-01-13 02:00
Concerning which-roles exist per above,  first I think there is some vocabulary updating needed for this list -- "dor-administrator", "sdr-administrator", "dor-apo-manager", "dor-apo-depositor", "dor-viewer"

• dor-administrator is the old name for sdr-administrator and can be dropped
• there should be an sdr-viewer for global viewing rights, replacing dor-viewer
• I don't think dor-apo-depositor has an implementation and we don't use it, so it can be dropped.
• there should indeed be a dor-apo-viewer

Other roles are postulated but not yet implemented. I've made that clearer on the consul page.

This would make the current list

   "sdr-administrator", "sdr-viewer", "dor-apo-manager", "dor-apo-viewer"

supporting read-only vs read/write access both globally and per-APO.

**Comment by darrenleeweber** [comment] 2016-01-20 00:37
These roles need to be fixed in dor-services, e.g.
```
> d = Dor::AdminPolicyObject.find(@druid)
=> #<Dor::AdminPolicyObject pid:"druid:ab987mn1234", >
> d.is_a? Dor::AdminPolicyObject
=> true
> d.can_view_content? ["dor-viewer"]
=> true
> d.can_view_content? ["dor-apo-viewer"]
=> false
> d.can_view_metadata? ["sdr-viewer"]
=> true
```

Until the issue is resolved in dor-services, i.e. https://github.com/sul-dlss/dor-services/issues/146, this bug will have to remain open.

**Comment by jmartin-sul** [comment] 2016-01-20 02:20
based on my current understanding, i think that https://github.com/sul-dlss/dor-services/issues/146 is a separate issue from this, and doesn't really block it, despite the fact that it also prevents users from seeing things they should be able to see.

this bug is about people who have access to a thing governed by a given APO, not people have have `dor-apo-viewer` access assigned in a governing APO.  dor-services 146 could prevent you from seeing objects you should be able to see, which you could also argue would prevent a user from seeing the governing APO for those objects.  but my impression is that you could fix dor-services 146, and then all that would magically work if this is already fixed.  and not fixing dor-services 146 wouldn't necessarily prevent you from seeing APOs that governed objects that you could actually get to already, which is what this is about.  and it seems to me that neither fix needs to account for the other in terms of altered code.

it's also totally possible that i'm misunderstanding or missing some subtlety here, in which case, corrections welcome.

**Comment by darrenleeweber** [comment] 2016-01-25 18:13
This should be fixed now by https://github.com/sul-dlss/argo/pull/474

**Comment by darrenleeweber** [comment] 2016-01-30 22:42
The PR in #474 now addresses comments above, i.e.
https://github.com/sul-dlss/argo/issues/76#issuecomment-169491847

The branch for PR #474 is deployed to argo-stage and it demonstrates the behavior required in
https://github.com/sul-dlss/argo/issues/76#issuecomment-170763057

**Comment by LynnMcRae** [comment] 2016-03-23 23:24
Validated this fix with a series of impersonates (mainly as sunetid:llam813) as well as manipulating Kam's workgroup memberships to get live testing of a person with specific APO-based privs coming on and off based on roles.  In all cases, access to governed items included access to the APO itself, with the ability to create collections for that APO.

**Comment by tingulfsen** [comment] 2016-03-23 23:45
I just added the "deployed to stage" label to signify that yesterday I deployed the cancancan branch that Chris made to stage (per request by Jack and Ben). So any testing done since that deployment on stage has been testing the cancan approach.

**Comment by LynnMcRae** [comment] 2016-03-24 00:51
Yes, it is this cancan work that I have been testing. As far as Ben and I are concerned, it is good to go.

**Comment by blalbrit** [comment] 2016-03-24 01:07
+1

**Comment by ndushay** [comment] 2016-03-29 00:12
waiting for @jkeck to sign off on sul-dlss/argo/pull/596.   After that, I *think* the code fix is already verified, so once it is in master, it can be deployed to argo prod.

**Comment by ndushay** [comment] 2016-03-30 18:57
#596 merged, so this will be in argo prod with the next deployment!

**Closed by ndushay** 2016-03-30 18:57 UTC
Labels: blocker, deployed to stage, must have, ready, verified in stage
