### ISSUE TITLE
(new Argo UI) pencil icons should not appear while an object is "in accessioning"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3093] opened 2022-02-09 23:30 UTC
When locking (closing) an object, the lock icon moves to the locked state immediately, but the pencil icons remain visible in the overview/details grid. The pencil icons should disappear at the same time that the lock gets locked, as it shouldn't be possible to edit items when they've been locked.

I think what's happening is that the pencils are not shown when the object has reached "Accessioned" but they are showing when the object is "in accessioning". I noticed this when recording my demo where I close an object to show the lock functionality.

![Screen Shot 2022-02-09 at 3 28 40 PM](https://user-images.githubusercontent.com/8975583/153307969-041062ed-46f4-4e47-bb66-10e5057a7c9b.png)

**Comment by jcoyne** [comment] 2022-02-10 03:54
I'm pretty sure this is a duplicate of #2900

**Comment by mjgiarlo** [comment] 2022-02-10 16:08
@jcoyne 💬 
> I'm pretty sure this is a duplicate of #2900

Can you confirm? I see #2900 is backlogged, too.

**Comment by mjgiarlo** [comment] 2022-02-10 17:42
Unassigning myself from this ticket for now.

**Comment by jcoyne** [comment] 2022-02-10 18:02
@mjgiarlo I'm not sure there's anything to sort out, only noting that the work should close two tickets and that there's some exploration that's already been done.

**Closed** 2022-02-15 18:53 UTC
Labels: new layout release
