### ISSUE TITLE
Number of objects in facets: match production or other solution

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#286] opened 2015-12-02 17:33 UTC
<img width="376" alt="screenshot 2015-12-02 09 30 39" src="https://cloud.githubusercontent.com/assets/796990/11538560/60995d4c-98d7-11e5-8e22-11e96a50cacf.png">

In Argo-stage, facets are limited to 10 objects, with no additional "more" links or ability to scroll or ctrl-f to find. If https://github.com/sul-dlss/argo/issues/224 is underdesigned or out of scope, we need to at least match the current production approach (just list 'em all).

**Comment by mejackreed** [comment] 2015-12-03 04:34
I'm pretty sure this was fixed with #285, but we should verify when there is more data in dev (a facet with > 20 unique values) or when @jmartin-sul updates his profiling branch from current develop (rebase)

**Comment by mejackreed** [comment] 2015-12-03 04:40
Scratch my previous comment. Looks like stage is up to date with that.

**Comment by blalbrit** [comment] 2015-12-03 04:44
Looking at prod:
<img width="1029" alt="screenshot 2015-12-02 20 41 55" src="https://cloud.githubusercontent.com/assets/796990/11552089/3c4eea3e-9935-11e5-86fc-da849c70f53c.png">

The little icon brings up a hover - but apparently in the wrong place for what it is showing (collection rights instead of defaultObjectRights). Let's take it out altogether at this point - we have trained people in what the options are and, if absolutely necessary, can put an enhancement ticket in at a later date.

**Comment by mejackreed** [comment] 2015-12-05 02:27
@blalbrit How many should we show before we show the more button? I'm thinking 10 - 20 should work ok?

**Comment by blalbrit** [comment] 2015-12-05 03:10
@mejackreed Agreed. 10-20 is fine. Not sure if exact number matters if the more button is there.

**Comment by LynnMcRae** [comment] 2015-12-07 20:42
The more button is not an effective substitute for just showing the whole list as it forces you into a painful and onerous paging experience without knowing where your entry lies alphabetically given leading articles and complicated names. See #201

**Comment by mejackreed** [comment] 2015-12-07 21:39
While "more" button is not an effective substitute for everything is this good enough for now? What the more button does do here:

 - it enables the rest of the facets to be found using the facet modal.
 - current (new argo) behavior only shows the first 10 without a more link.

Is this good enough to unhide facets until #201 can be appropriately addressed?

**Comment by LynnMcRae** [comment] 2015-12-08 01:30
I think #201 makes it clear that the BL "more" is useless for our collection and APO facets.  We can't have a release with that approach since it would render those facets essentially non-functional.

**Comment by cbeer** [comment] 2015-12-08 01:34
What about the paginated facets renders them useless?

**Comment by LynnMcRae** [comment] 2015-12-08 01:42
#201 provides examples ... you'd be guessing on where in the page sequence something might lie, fishing about, not even certain you are looking for the right leading letter.  It's a non-starter user experience, and a no-brainer compared to the ease of finding what you want with cmd-F after opening the facet showing the full list.

**Comment by cbeer** [comment] 2015-12-08 01:44
Ok. And what user stories are we trying to address? An obvious one seems like discovering items collections. Are there others?

**Comment by LynnMcRae** [comment] 2015-12-08 02:07
The majority of sessions in Argo likely start with a project-related focus on items in a collection or APO.  Those records become the target of analysis (opening up other facet values to see what the data looks like), or tracking (opening up the workflow grid), or remediation (blue buttons or bulk updates), or extraction, or release. It will be critical to the upcoming collection profile feature. Note that SDR admins, DLSS developers & PSM and a few other critical players like Shelley see the full lists in all their glory (500+). Some users, e.g., lab folks,  get a more reasonable set (100-200?), while curators like the maps folks might see <100. There are nice ideas for really spiffy "more" improvements if not other means for targeting collections, but we just need the old behavior, which works fine, for this release.

**Comment by mejackreed** [comment] 2015-12-08 02:14
@LynnMcRae Agreed that it is important for them to be able to access the collections as a jumping off point. Is there a reason to hold up #311 though?

Currently with Argo develop branch as it stands right now, there isn't a quick fix to "get the old behavior". So I see we have 3 options (open to others):
 - merge #311 and get the "more" functionality
 - spend time to get the old behavior
 - spend time to implement the behavior we actually want

Though CTRL+F can help find things from a long list on a page, I think we can do better. I'd prefer to implement the better approach, with the "more" being merged as a stop gap until that can come.

**Comment by LynnMcRae** [comment] 2015-12-08 02:26
No reason not to move forward as we need the “more” in general.  Most facets have <10 values but would like to inspect a handful, e.g. Genre, to see if something like 20 would make sense overall for some lists at the boundary (I’d check tonight except I got a new iPhone and can’t set up two-step authentication on the new device because you need two-step authentication to do so … I’m sure it’s just me).  If we can do a better behavior with the time we have, all the better!

Lynn

**Comment by atz** [comment] 2015-12-08 18:51
Reproducing the old behavior is trivial: set the limit arbitrarily high.  I agree it is not the best for performance (in general we have too many facets in too many places), but there is no technical difficulty in how to obtain it.  It also makes the UI clunky, but if the users decide they prefer that functionality, then they prefer that functionality.

**Comment by cbeer** [comment] 2015-12-08 18:52
Do the users actually prefer that functionality? Or have we just never given them a better alternative?

**Comment by atz** [comment] 2015-12-08 20:21
@cbeer Reading Lynn's comment, they prefer the functionality to the implementation proposed for acceptance.  We can assume a "better alternative" would be preferred by definition for its being better.  It does not, at this time, exist.  Doing it properly is bigger scope than this issue and this final sprint can accommodate.  Also should probably be done at the blacklight level since we aren't the only ones with large facet valuesets.

**Comment by LynnMcRae** [comment] 2015-12-09 17:56
Yes, exactly so. cmd-F works but is no one’s idea of a good U. But it’s at its worst to us as SDR Admins, and it took the urgency away from doing something different. As Joe points out, we’d rather work on a useful shared contribution to hydra/blacklight/discovery and weren’t remotely close to being able to do that before now.

Lynn

**Closed** 2015-12-11 18:45 UTC
Labels: +1, bug, feature parity, in progress
