### ISSUE TITLE
Create a dashboard for sidekiq monitoring

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/argo#1867] opened 2020-03-24 18:21 UTC
We have many sidekiq instances. It would be great if there was one page (dashboard) that the first responder to look at to determine if there are any problems.

**Comment by ndushay** [comment] 2020-04-02 19:22
I believe this is a duplicate of sul-dlss/dor-services-app#552 so I am closing.

**Comment by jcoyne** [comment] 2020-04-02 19:27
Not a duplicate.

**Closed** 2021-04-06 03:41 UTC
