### ISSUE TITLE
Analysis of profiling data

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#250] opened 2015-11-23 19:09 UTC

**Comment by jmartin-sul** [comment] 2015-11-23 22:58
@tingulfsen

here's the profiling tutorial where i discovered the callgrind output format (which you can get from the `CallTreePrinter` in RubyProf):  https://www.coffeepowered.net/2013/08/02/ruby-prof-for-rails/

as suggested by that tutoral, on OS X you can use the QCacheGrind GUI to get a visual representation of the callgrind output.  i was able to install that easily from the command line by just running `brew install qcachegrind` (you can run it using `qcachegrind`, gets added to the default `PATH` automatically).

here's some more general info i found on using the callgrind format for analysis:
* some info on cg_merge as a tool to combine cachegrind files (and cg_diff as a tool to compare them).  also lots of instruction that's extraneous to us (since it's focused on using valgrind's command line cachegrind tool to profile command line executables):  http://valgrind.org/docs/manual/cg-manual.html#cg-manual.profile
* http://stackoverflow.com/questions/6683916/how-to-generate-a-simple-callgraph-of-a-multiprocess-application-with-callgrind
* further documentation on KCacheGrind/QCacheGrind (though it doesn't mention homebrew as a possible installation method, as far as i can tell):  https://kcachegrind.github.io/html/Documentation.html

currently, Argo::Profiler puts output in the `log/profiler/` directory.  the reindexing mechanism has optional profiling functionality built in (which defaults to being switched off), but in other cases, you'd have to manually wrap the code you wanted to profile in an Argo::Profiler block.

once this is all ironed out, it'd probably be good to have a short set of README-like instructions on basic built-in argo profiling capabilities (probably couldn't hurt to do the same for indexing).  maybe in a separate file linked from the README, but we can figure that out later.

**Comment by jmartin-sul** [comment] 2015-11-23 23:04
erin mentioned that new relic offers some number of pro licenses for free to non-profit institutions, so we might also be able to take advantage of that for our profiling needs.  but since we have no definite estimates on if and when that'll get switched on, and since it'd be nice to have robust in-app profiling (without having to rely on network calls to a third-party or the service level they provide at our price point), i think it's still well worth exploring the callgrind stuff in the meantime.

**Comment by drh-stanford** [comment] 2015-11-24 18:54
if needed, i can help review the profile output once it's collected

**Comment by jmartin-sul** [comment] 2015-11-24 21:56
i've just started a run of the full reindex on argo-stage-b using the rake task.  it seems be be going smoothly (other than slowing down the VM).  callgrind files are being generated as reindexing batches complete, and are available in `log/profiler`.  you want the ones from today (11/24) onward.

**Comment by drh-stanford** [comment] 2015-11-24 22:28
Here's a tidbit... Lots of time spent in the Solrizer itself... probably because we have hundreds of fields per document?

![screen shot 2015-11-24 at 2 24 24 pm](https://cloud.githubusercontent.com/assets/1861171/11382560/7ba6cc4e-92b7-11e5-9268-23ab4d188989.png)

**Comment by drh-stanford** [comment] 2015-11-24 22:44
there's 4 calls to the workflow service REST API per object

```
"GET /workflow/dor/objects/druid:ty100sj3722/workflows/ HTTP/1.1" 200 98
"GET /workflow/dor/objects/druid:ty100sj3722/lifecycle HTTP/1.1" 200 42
"GET /workflow/dor/objects/druid:ty100sj3722/lifecycle HTTP/1.1" 200 42
"GET /workflow/dor/objects/druid:ty100sj3722/lifecycle HTTP/1.1" 200 42
```

![screen shot 2015-11-24 at 2 42 42 pm](https://cloud.githubusercontent.com/assets/1861171/11382934/a8c5e6b8-92b9-11e5-82a7-4a1d325f02aa.png)

**Comment by drh-stanford** [comment] 2015-11-24 22:52
Here's the datastream `to_solr` calls... once per object (10 objects per batch, right?). It's a little strange that `ContentMetadataDs.to_solr` is slow... Looks like the Om is piggy?

![screen shot 2015-11-24 at 2 48 04 pm](https://cloud.githubusercontent.com/assets/1861171/11383068/7e7eef3e-92ba-11e5-8e88-273d40a8177e.png)

![screen shot 2015-11-24 at 2 50 56 pm](https://cloud.githubusercontent.com/assets/1861171/11383100/d068c59a-92ba-11e5-8250-e3604639af72.png)

**Comment by mejackreed** [comment] 2015-11-24 22:55
:+1: for the analysis so far

**Comment by drh-stanford** [comment] 2015-11-24 22:57
And overall we can rule out the `RSolr.add` as a bottleneck. The `to_solr` is the bottleneck (as expected).

![screen shot 2015-11-24 at 2 55 52 pm](https://cloud.githubusercontent.com/assets/1861171/11383209/82c33090-92bb-11e5-9ef9-118e38583dd8.png)

**Comment by darrenleeweber** [comment] 2015-11-25 02:08
Agree that rest-client does not use persistent connections.  I've raised the issue of HTTP client performance before and we can see here that it's important.  See, for example,
https://bibwild.wordpress.com/2012/04/30/ruby-http-performance-shootout-redux/

**Comment by darrenleeweber** [comment] 2015-11-25 02:24
Wondering whether there is any way to gather all the datastreams into one XML doc and then run one XSLT on it in some fashion that is faster than all the individual datastream `to_solr` calls.  (Novice question, need to look closer at code details.)

**Comment by darrenleeweber** [comment] 2015-11-25 02:29
Most, if not all, of the `to_solr` methods are in dor-services, i.e.
Quick look at https://github.com/sul-dlss/dor-services/search?utf8=%E2%9C%93&q=to_solr

**Comment by darrenleeweber** [comment] 2015-11-25 02:34
I cringe a little when I see code like this:
https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/workflow_definition_ds.rb#L49-L55
The xpath is run every single time - that code could assign to an instance variable once and be done, right?

**Comment by mejackreed** [comment] 2015-11-25 11:57
Yep, memoization is your friend here.

**Comment by atz** [comment] 2015-11-25 21:31
There *is* keep-alive for rest-client more than 2 years ago:
https://github.com/duncan-bayne/rest-client/commit/af5ceb0c18115deb468d59343d65668f1ffa7f64

But not yet merged for whatever reason:
https://github.com/rest-client/rest-client/pull/171

**Comment by mejackreed** [comment] 2015-11-25 21:33
This comment: https://github.com/rest-client/rest-client/pull/171#issuecomment-87360475

>Since ruby 2.0, the net/http in the stdlib support keep alive out of the box. You simply need to set the keep_alive_timeout property.

**Comment by atz** [comment] 2015-11-25 21:36
Apparently that can introduce problems with exception handling and other expectations of API behavior.  But it is worth our giving it a try.

**Comment by drh-stanford** [comment] 2015-11-25 21:37
I've been looking into this and the problem is that you have to call `Net::HTTP::Persistent` class when you initialize the socket, at least in that PR.

It looks like you can access the connection directly to set the flag, as shown here:

https://github.com/dylanahsmith/net-http-persistent/blob/1dcdf06f111227f0396afd9b12ab94bea2c636e2/lib/net/http/persistent.rb#L634

Also, both the dor-workflow-service and rubydora (we're on 1.6.5) use the rest-client gem.

https://github.com/projecthydra/rubydora/blob/v1.6.5/rubydora.gemspec#L20

**Comment by atz** [comment] 2015-11-25 21:52
Ruby 2.0 net/http `keep_alive_timeout` defaults to 2 seconds, so we can definitely bump that up.  But that also seems to suggest that keep alive is in fact enabled by default.

**Comment by drh-stanford** [comment] 2015-11-25 21:52
I tried modifying dor-workflow-service like so, but the keep-alive option isn't going through as far as I can tell:

```ruby
--- a/lib/dor/services/workflow_service.rb
+++ b/lib/dor/services/workflow_service.rb
@@ -466,6 +466,7 @@ module Dor
         @@handler = Proc.new do |exception, attempt_number, total_delay|
           @@logger.warn "[Attempt #{attempt_number}] #{exception.class}: #{exception.message}; #{total_delay} seconds elapsed."
         end
+        params[:keep_alive_timeout] = 30 if Object::RUBY_VERSION[0] == 2 && opts[:no_keep_alive].nil?
         @@resource = RestClient::Resource.new(url, params)
       end
```

**Comment by atz** [comment] 2015-11-25 22:13
If WFS service is HTTP 1.0 only, then we would expect that it wouldn't matter.

**Comment by drh-stanford** [comment] 2015-11-26 00:11
We do have a process size issue for the delayed_job process. It's calling `Argo::Application.initialize!` which sucks in the whole rails app. The fix for that is to only include the environment that's required for the batch jobs.

**Comment by jmartin-sul** [comment] 2015-11-26 00:27
in the first 40 minutes or so of testing on argo-stage-b with RubyProf disabled, the workers appear to be much more stable, and appear to be processing things much more quickly.  for instance, just over 1000 items have been added to the index in the last 45 minutes, which means that 100+ batches had to be processed (since batch size is 10 objects or less).  for comparison, in all of yesterday's testing, especially with items, it was hard to get workers to stay alive for more than 30 min or so, and we only processed 500-something items (plus probably 100-something other objects).  much of that throughput problem was due to workers dying (not just their processing rate while alive), but the stability improvement is obviously important in and of itself.

not surprising, i guess.  i definitely remember profiling java code, and seeing it become more unstable due to the overhead introduced by profiling.  unfortunate that profiling is diciest when it's most needed, but so it goes.

anyway... we do have a bunch of profiling data at this point, and it should be at least somewhat representative of the characteristics of what we're indexing.  so i'd vote for leaving this running without profiling for a while, and seeing what kind of stability and throughput we get.  we can analyze our current profiling info for possible dor-services optimizations.

as @drh-stanford points out, the delayed_job processes are still huge, because they're essentially spinning up a rails app for each one.  and as he pointed out just now while meeting with @atz and i on this issue, the indexing jobs are still *leaking* memory, even without profiling, and that's on top of the already large memory requirements of rails.

anyway, progress.  argo-stage-b now has just over 2000 indexed items, whereas it had just over 500 less than an hour ago.

**Comment by jmartin-sul** [comment] 2015-11-26 02:01
@drh-stanford (and a bit later @mejackreed) also noticed that argo-prod-b and argo-stage-b have the same resource allocation as argo-dev (8 CPU/4 GB, vs. 12 CPU/16 GB for real prod).  @drh-stanford filed a SAR ticket to get argo-stage-b and argo-prod-b the same resource allocation as argo-prod.

the resource allocation might help explain the ridiculous increase in indexing time when testing was first done back in may (5 weeks, vs. last september's full reindexing in 2.5ish days).   i guess some of us assumed that a "clone" of production would be a clone in resource allocation also (i didn't even think to ask about that).  but i can see how if someone thought the setup was just for initial functional testing of the schema against good fedora data, it'd make a lot of sense to not waste a bunch of excess resources on it.  so... i'm pretty excited to see what indexing on argo-stage-b and argo-prod-b look like with argo-prod levels of memory and processor allocation.  we've indexed just over 5000 objects in the last 2 hrs, so if we round down to 2500/hr, that's 300 hrs to do 750k objects, which means 12.5 days to do all of dor-prod (and that's with the computing resources of argo-dev).  that was the same rate i estimated an hr ago, which makes me optimistic about it staying consistent.  and it does seem plausible to me that the delayed job approach could better than halve the time for a full reindex, since it doesn't do the whole roundabout (and even more fragile) thing of giving pid lists to karaf, so that karaf can queue requests to the /dor/reindex URL on argo.

as a side note, i think it's as funny as it is frustrating that we might've been worried about a performance problem that was a result of our investigating a performance problem that we might've just been able to chalk up to mismatched expectations re: how much computing power a VM should've had.

**Comment by drh-stanford** [comment] 2015-11-26 04:15
See SAR-3021 for VM resizing

**Comment by drh-stanford** [comment] 2015-12-02 18:15
we upgraded to 32GB.  i did some memory profiling and here's what i'm seeing for a single reindex object

```
retained memory by gem
-----------------------------------
   2475909  newrelic_rpm-3.14.0.305
    157992  mods-2.0.3
     98038  nom-xml-0.5.4
     68412  ruby-2.2.2/lib
     13840  argo/app
      4344  nokogiri-1.6.6.4
      2720  activesupport-4.2.4
      2656  webmock-1.17.4
      1576  addressable-2.3.5
      1064  actionview-4.2.4
       928  rdf-1.1.17.1
       784  actionpack-4.2.4
       504  active-fedora-6.7.3
       449  stanford-mods-1.2.1
       136  dor-services-d96fb43e0854
       120  rsolr-1.0.13```

**Comment by mejackreed** [comment] 2015-12-02 18:49
Does it make sense to disable new relic on stage temporarily? Could be added to `staging.local.yml` on box:

```yaml
NEWRELIC:
  ENABLED: false
```

**Comment by drh-stanford** [comment] 2015-12-02 19:18
yes, absolutely. @jmartin-sul has a laundry list of next steps, one of which is to disable newrelic to see how that goes

**Comment by drh-stanford** [comment] 2015-12-02 19:25
NewRelic indicates that these objects are released by a background thread after a certain amount of time. see https://discuss.newrelic.com/t/nr-looks-leaking-the-objects/30305

**Comment by mejackreed** [comment] 2015-12-02 19:35
Awesome.. great job guys!

**Closed** 2015-12-07 17:26 UTC
