### ISSUE TITLE
bulk metadata error: No such file or directory @ rb_sysopen - log/workflow_service.log

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2114] opened 2020-06-09 18:55 UTC
**Describe the bug**
Bulk metadata uploads are failing with the error:
`No such file or directory @ rb_sysopen - log/workflow_service.log`

This may be related to #2104 where the same error message appears for a different type of bulk job.

**User Impact**
It's not possible to make bulk updates to metadata.

**Additional context**
Only one bulk metadata upload job has been run today and it has failed. Jobs run yesterday (2020-06-08) succeeded.

Today's failed job is on this APO: https://argo.stanford.edu/apos/druid:fp165nz4391/bulk_jobs

I've done a little investigation on the Argo server. In `/workspace/bulk` there are actually three folders for this bulk job, suggesting that the server retried a couple of times. The user only submitted the job once. The folders are at these paths:

```
/workspace/bulk/druid:fp165nz4391/2020_06_09_17_39_10_748
/workspace/bulk/druid:fp165nz4391/2020_06_09_17_45_21_376
/workspace/bulk/druid:fp165nz4391/2020_06_09_17_51_39_847
```

The log.txt file shows this error for each druid on the spreadsheet:
```
argo.bulk_metadata.bulk_log_error_exception druid:bp689yg5580
No such file or directory @ rb_sysopen - log/workflow_service.log
["/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:752:in `initialize'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:752:in `open'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:752:in `create_logfile'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:746:in `rescue in open_logfile'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:742:in `open_logfile'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:736:in `set_dev'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:671:in `initialize'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:387:in `new'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/logger.rb:387:in `initialize'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/services/workflow_client_factory.rb:6:in `new'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/services/workflow_client_factory.rb:6:in `build'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/services/apply_mods_metadata.rb:132:in `status'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/services/apply_mods_metadata.rb:117:in `in_accessioning?'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/services/apply_mods_metadata.rb:29:in `apply'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/jobs/modsulator_job.rb:98:in `block in update_metadata'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:238:in `block in each'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `upto'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/nokogiri-1.10.9/lib/nokogiri/xml/node_set.rb:237:in `each'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/jobs/modsulator_job.rb:89:in `update_metadata'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/jobs/modsulator_job.rb:54:in `block in perform'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/jobs/modsulator_job.rb:32:in `open'", "/opt/app/lyberadmin/argo/releases/20200512180459/app/jobs/modsulator_job.rb:32:in `perform'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/execution.rb:39:in `block in perform_now'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n.rb:313:in `with_locale'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in `instance_exec'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/logging.rb:26:in `block (4 levels) in <module:Logging>'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `block in instrument'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:168:in `instrument'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/logging.rb:25:in `block (3 levels) in <module:Logging>'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/logging.rb:46:in `block in tag_logger'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:28:in `tagged'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/tagged_logging.rb:71:in `tagged'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/logging.rb:46:in `tag_logger'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/logging.rb:22:in `block (2 levels) in <module:Logging>'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in `instance_exec'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:136:in `run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/execution.rb:38:in `perform_now'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/execution.rb:24:in `block in execute'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:109:in `block in run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/railtie.rb:28:in `block (4 levels) in <class:Railtie>'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/execution_wrapper.rb:87:in `wrap'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/reloader.rb:73:in `block in wrap'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/execution_wrapper.rb:87:in `wrap'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/reloader.rb:72:in `wrap'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/railtie.rb:27:in `block (3 levels) in <class:Railtie>'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in `instance_exec'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.4.2/lib/active_support/callbacks.rb:136:in `run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/execution.rb:22:in `execute'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/activejob-5.2.4.2/lib/active_job/queue_adapters/delayed_job_adapter.rb:42:in `perform'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:81:in `block in invoke_job'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/honeybadger-4.6.0/lib/honeybadger/plugins/delayed_job/plugin.rb:37:in `block (2 levels) in <class:Plugin>'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79:in `block in add'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:78:in `invoke_job'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:230:in `block (2 levels) in run'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/timeout.rb:103:in `timeout'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:230:in `block in run'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:229:in `run'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:213:in `block in work_off'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:212:in `times'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:212:in `work_off'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:175:in `block (4 levels) in start'", "/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:174:in `block (3 levels) in start'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:173:in `block (2 levels) in start'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:172:in `loop'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:172:in `block in start'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:79:in `block in add'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/worker.rb:171:in `start'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/command.rb:137:in `run'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/command.rb:125:in `block in run_process'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/daemons-1.3.1/lib/daemons/application.rb:275:in `block in start_proc'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/daemons-1.3.1/lib/daemons/daemonize.rb:84:in `call_as_daemon'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/daemons-1.3.1/lib/daemons/application.rb:279:in `start_proc'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/daemons-1.3.1/lib/daemons/application.rb:305:in `start'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/daemons-1.3.1/lib/daemons/controller.rb:56:in `run'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/daemons-1.3.1/lib/daemons.rb:199:in `block in run_proc'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/daemons-1.3.1/lib/daemons/cmdline.rb:121:in `catch_exceptions'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/daemons-1.3.1/lib/daemons.rb:198:in `run_proc'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/command.rb:123:in `run_process'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/delayed_job-4.1.8/lib/delayed/command.rb:98:in `daemonize'", "bin/delayed_job:6:in `<top (required)>'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'", "/usr/local/rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'", "/usr/local/rvm/gems/ruby-2.6.3/bin/bundle:23:in `load'", "/usr/local/rvm/gems/ruby-2.6.3/bin/bundle:23:in `<main>'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'", "/opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'"]
```

**Comment by jcoyne** [comment] 2020-06-09 18:57
@andrewjbtw is this a duplicate of #2104

**Comment by andrewjbtw** [comment] 2020-06-09 19:07
It could be the same underlying cause but it's a different type of bulk job, run from a different page in Argo.

**Closed** 2020-06-15 18:38 UTC
Labels: bug
