### ISSUE TITLE
Edits to multiple object datastreams are not being saved

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#2375] opened 2021-01-28 19:16 UTC
**Describe the bug**
Edits to some object datastreams made via Argo are not being saved. Argo shows an edit button, allows users to edit, and then reports success, but the datastream remains unchanged.

So far, I have found that the following datastreams cannot be edited:

- administrativeMetadata (APO)
- versionMetadata (all objects)
- RELS-EXT (all objects)
- roleMetadata (all objects that have it)

**User Impact**
Users cannot edit these datastreams, which is the only way to make certain changes that can only be made by editing datastreams.

**To Reproduce**
Steps to reproduce the behavior (APO example):
1. Go to an APO
2. Click on administrativeMetadata
3. Click on edit
4. Make a valid edit (such as adding or removing a collection from the <registration> section)
5. Save the edit
6. See Argo report success
7. See that the datastream hasn't actually been changed.

**Expected behavior**
If the edit button shows, then the edits should be saved.

**Comment by jcoyne** [comment] 2021-01-28 19:17
I think the problem here is that the API supports this, but the client does not yet: https://github.com/sul-dlss/dor-services-client/blob/096fbdd8a7a15ee8ff871b0a3597799c0febcd74/lib/dor/services/client/metadata.rb#L28

**Comment by andrewjbtw** [comment] 2021-01-28 19:17
Originally reported on Slack:
https://app.slack.com/client/T044BUE0A/C0EAZ09QF/thread/C0EAZ09QF-1611792977.026600

In that thread @jcoyne points to dor-services-client:

"I think the problem here is that the API supports this, but the client does not yet: https://github.com/sul-dlss/dor-services-client/blob/096fbdd8a7a15ee8ff871b0a3597799c0febcd74/lib/dor/services/client/metadata.rb#L28 "

**Comment by andrewjbtw** [comment] 2021-01-29 17:18
Noticed that edits to the RELS-EXT datastream are also not being saved. I've revised the title of this issue.

**Comment by andrewjbtw** [comment] 2021-02-10 17:54
I've updated this ticket with a longer list of datastreams where the edit button shows but edits are not saved.

**Comment by jcoyne** [comment] 2021-02-10 21:17
Note that roleMetadata is only available on APOs.

**Comment by andrewjbtw** [comment] 2021-02-10 21:23
It's a part of Hydrus items: https://argo.stanford.edu/view/druid:bb284rg5424

**Comment by ndushay** [comment] 2021-02-18 22:45
Deployed a fix to stage for Andrew to test.  This should work for all BUT the roleMetadata datastreams.

**Comment by jcoyne** [comment] 2021-02-18 22:53
@andrewjbtw would it be possible to turn off the direct editing of the `roleMetadata` datastream or is direct edits the only way to accomplish a specific expressed use case?

**Comment by ndushay** [comment] 2021-02-18 23:55
dor-services-client v6.19.2 released;  the fix should be applied to Argo with the dependency updates on Monday.

The roleMetadata editing is NOT addressed by this.

**Comment by andrewjbtw** [comment] 2021-02-19 00:25
Since the roleMetadata on items won't mean anything after Hydrus and Fedora go away we can leave it out. In the rare case an edit needs to be made again before Hydrus retirement, that can still be done without Argo. I checked with Hannah and Amy and they're ok with this.

**Comment by peetucket** [comment] 2021-02-23 22:29
Closing after recent deploy, unless the problem is confirmed to still exist

**Closed by peetucket** 2021-02-23 22:29 UTC
Labels: bug
