### ISSUE TITLE
Items in the collection druid:xt225ms0491 cannot be opened for modification despite having "Accessioned" status

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#1726] opened 2019-11-12 21:57 UTC
**Describe the bug**
Reported in the Slack channel: a curator has been unable to update metadata for items in the collection: druid:xt225ms0491 They were attempting to make this update using the replayable spreadsheet. The log can be found here: https://argo.stanford.edu/apos/druid:xw330hm5827/bulk_jobs

According to the log, some of the druids were updated and new data saved, but other druids could not be opened. According to the user, none of the changes were saved and none of the updates have gone through.

I checked every druid in the collection by opening each one in Argo and found that they all have the status of "Accessioned" and all of their workflows are marked as "completed". This should mean that they can be opened for modification, but on each druid page the button for "open for modification" is grayed out:

![Screen Shot 2019-11-12 at 1 47 53 PM](https://user-images.githubusercontent.com/8975583/68713617-1d497800-0553-11ea-8496-c96905122653.png)

I looked at the releaseWF for a sampling of the objects and they are missing the step for "update-marc":

![Screen Shot 2019-11-12 at 1 49 54 PM](https://user-images.githubusercontent.com/8975583/68713721-57b31500-0553-11ea-9c06-b03cc650b997.png)

"update-marc" is not a new workflow step but it has been affected by the recent change in workflow steps. See here: https://github.com/sul-dlss/workflow-server-rails/pull/274 It's possible that this step needs to be added and completed before the objects can be opened.

**User Impact**
It is not possible to update these items with new data.

**To Reproduce**
1. Go to any item in this collection: https://argo.stanford.edu/catalog?f%5Bis_member_of_collection_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Axt225ms0491
2. Attempt to open the item for modification.

**Expected behavior**
Objects with completed workflows and an Accessioned status should be openable for modification.

**Additional context**

There may be other objects affected by this issue beyond this collection and it would probably be worth the time to identify and fix them instead of waiting for users to report problems.

**Comment by blalbrit** [comment] 2019-11-12 22:54
This seems to be caused by conflicting duplicate publish-complete steps in the active_version workflow (one with completed, one with waiting). Manually updated https://argo.stanford.edu/view/druid:bb182ts0923 and confirmed setting the waiting step to completed fixes the issue.

**Comment by jcoyne** [comment] 2019-11-12 22:56
@jmartin-sul looks like there's a missing constraint in the workflow service.

**Comment by peetucket** [comment] 2019-11-14 23:54
This collection is now fixed.  Revisiting sul-dlss/workflow-server-rails#40 is a good idea, but would require cleaning up any other dupes in the database first.

**Closed** 2019-11-14 23:54 UTC
Labels: bug

**Comment by ndushay** [comment] 2019-11-15 19:17
@peetucket will timebox trying to do validation proactively.
@jmartin-sul will do db query to find data that needs to be remediated

**Comment by peetucket** [comment] 2019-11-15 21:32
turned out validation was easy thanks for rails: https://github.com/sul-dlss/workflow-server-rails/pull/283
