### ISSUE TITLE
Bulk Download Not Functioning on Large Queries

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#652] opened 2016-03-04 23:52 UTC
See https://argo.stanford.edu/catalog?f%5Bnonhydrus_collection_title_ssim%5D%5B%5D=Stanford+Historical+Photograph+Collection with 14K objects. This is one of the key use-cases for bulk download support so need to determine if it's a size issue or something else happening.

**Comment by tingulfsen** [comment] 2016-03-07 16:28
This is a size issue. When starting the bulk download job, we create a list of all the druids to download. This list is stored within MySQL, which barfs on the long list. We may be able to alter the code to pass the druids in a more sane way to the job. The crash happens on this line:

https://github.com/sul-dlss/argo/blob/master/app/models/bulk_action.rb#L54

The job_params hash has too many elements.

@blalbrit  if you can find a way to reduce the number of objects by manually chunking the download job, that could be a quick workaround for now.

**Comment by blalbrit** [comment] 2016-03-07 16:58
@tingulfsen - I suppose our stakeholders can be forced to chunk the download job, but there is no clear mechanism for that in large, undifferentiated collections like the one in question where there *are* 25K objects that need to be downloaded as a group and are not already sub-divided in any way. Maybe they could generate the list of druids, and then paste in 1000 or max-number-downloadable at a time?

Do you have any way of knowing what max-number-downloadable actually is?

@LynnMcRae - do you see any other work-arounds than forcing a stakeholder to create arbitrary groupings of content in order to be able to download large collections?

**Comment by LynnMcRae** [comment] 2016-03-07 17:39
Is the druid list simply saved as a column in the table? Given the 64k row size limit in MySql, we should have known that would impose a druid list limit around 5000. Can it be saved as an artifact in the file system instead? It's not really a good use of the database in the first place if the facility is meant to scale arbitrarily, which was a requirement for the same reasons we run it in the background instead of in the user's session.  @tingulfsen Did you have other ideas for getting past this limit?

**Comment by drh-stanford** [comment] 2016-03-07 18:24
In MySQL, the `:text` column can be changed to `:longtext` so that it turns into a 4G blob rather than a 64k blob.

**Comment by tingulfsen** [comment] 2016-03-07 22:24
Thanks, @drh-stanford - that's a good idea. I'm a little reluctant to alter the MySQL schema because it is not really within Argo's domain. It's actually defined within DelayedJob/ActiveJob. So while fixing the schema is a possibility, I'm more inclined to change the ways arguments are passed into perform_later().

**Comment by jkeck** [comment] 2016-03-15 22:28
Hmm, if I understand correctly, the column that holds this information for delayed job is already a text type (https://github.com/sul-dlss/argo/blob/master/db/migrate/20150619200031_create_delayed_jobs.rb#L6).

So I wonder if it's even too large for that column type (although I doubt 4G).  Is there a bug reported in squash that would allow me to see a backtrace?

**Comment by mejackreed** [comment] 2016-03-15 22:48
Here you go @jkeck https://sul-squash.stanford.edu/projects/argo/environments/production/bugs/70

**Comment by jkeck** [comment] 2016-03-15 23:26
FWIW, checking the first instance of the error it looks like 14,615 druids alone takes up over 270kb (which is much higher than MySQLs default `text` limit).

**Comment by tingulfsen** [comment] 2016-03-18 22:34
I have deployed a branch to argo-stage that I think should fix this.

**Comment by ndushay** [comment] 2016-03-29 00:09
@tingulfsen will prepare a PR to merge the code fix from the appropriate branch to master.  Since the fix is already verified, once it is in master, it can be deployed to argo prod.

**Comment by ndushay** [comment] 2016-03-30 18:48
copying over a comment from @LynnMcRae which was on PR #707:

From a large run this afternoon:
![screen shot 2016-03-29 at 6 05 34 pm](https://cloud.githubusercontent.com/assets/1824732/14128786/ec80f848-f5d8-11e5-82b1-9007afac6d15.png)

- From the download file, all but one object's descMetadata was downloaded
- From the Log, there was one error midway with detail diagnostics, then the run seemed to resume just fine (Tommy has the log)
- So the numbers reported are off but the utility definitely want way past the older ~500 item limit and processed them correctly.

**Comment by LynnMcRae** [comment] 2016-03-30 21:12
A series of graduated tests in stage, was able to reproduce the above anomaly with object counts with another large list. In all cases the actual downloaded MODS looks good.  We observed that the Mac is not happy with the druid:xxxxxxx  filenames in the zip file but shows them as druid/xxxxxxx in the finder instead. Not an issue we are concerned about at present.
![screen shot 2016-03-30 at 1 45 42 pm](https://cloud.githubusercontent.com/assets/1824732/14157749/647e97bc-f681-11e5-96da-312cf4dfe640.png)

**Comment by LynnMcRae** [comment] 2016-03-30 23:07
Success count issue moved to #711

**Comment by ndushay** [comment] 2016-03-30 23:30
I'm closing this ticket;  new comments pertaining to file counts should go in #711.

**Closed by ndushay** 2016-03-30 23:30 UTC
Labels: bug, deployed to stage, must have, verified in stage
