### ISSUE TITLE
Manage Release dialog uses dc:title from object

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#910] opened 2016-12-15 22:22 UTC
The title found in the DC datastream is set at registration time but never changed so often does not reflect the current title of the object. For example, all Hydrus objects start with an objectLabel and dc:title of "Hydrus" before they get the user-supplied title in descMetadata.  Example: https://argo.stanford.edu/view/druid:vg815yn1511

The Manage Release dialog should use the actual title from the object, from descMetadata or from its solr reflection.

**Comment by blalbrit** [comment] 2017-07-24 18:06
@tingulfsen - another example of this, which prompted raising the priority on this ticket, is here:

https://argo.stanford.edu/view/druid:jc193gx3855

We have manually updated the DC to reflect what was desired, but it had a different dc:title initially which was being passed on to SearchWorks (which wreaks havoc).

The code that seems to be populating that title is here: https://github.com/sul-dlss/dor-services-app/blob/56ebef441ba4b96e04008933c6490dff7db00eba/app/models/dor/update_marc_record_service.rb#L124

The coll.label call apparently goes to dc and gets dc:title. Neither @LynnMcRae nor I could figure out exactly what coll.label is - but it seems like that's where to start.

**Comment by blalbrit** [comment] 2017-07-24 18:09
re: ^^ - the dc:title previously looked like this:

  <dc:title>Phase 3 (city plans)</dc:title>
  <dc:identifier>druid:jc193gx3855</dc:identifier>

And that bad title was what was being passed to SW.

**Comment by blalbrit** [comment] 2017-07-25 01:01
@tingulfsen - @ndushay gave me an update on this that suggested the problem might already be fixed. There is a simple way to test this - change a title on a collection, and release the content to SW to see if we produce a "bad" title. Of course, the only environment we can really do this in is -prod - so I'll make a change to a production collection and see what updateMARC does with it.

**Comment by blalbrit** [comment] 2017-07-25 17:31
Okay - here is what I'm doing to test:

Test for UPDATE_MARC pulling from correct field

1) created new collection https://argo.stanford.edu/view/druid:jv359dd3912 (Pirages2017)
2) add child objects to collection (https://argo.stanford.edu/catalog?f%5Bexploded_tag_ssim%5D%5B%5D=Project+%3A+Stanford+Medieval+Manuscripts+%3A+Pirages2017)
3) updated title to something else (confirm that DC remains the same)
4) release collection to SW
5) if collection title=correct, close ticket; if collection title!=correct, work ticket

**Comment by blalbrit** [comment] 2017-07-25 17:33
1-4 are complete, waiting for objects to appear in SW. Preliminary results (orthogonal to this ticket since it's really just showing Argo behavior):
Collection object with updated title:
![screenshot 2017-07-25 10 30 33](https://user-images.githubusercontent.com/796990/28585242-87746d5e-7124-11e7-9ac5-3fda2704658d.png)

Individual object, collection field still shows old title:
![screenshot 2017-07-25 10 30 40](https://user-images.githubusercontent.com/796990/28585264-9aaa2224-7124-11e7-974c-017f588739ed.png)

**Comment by blalbrit** [comment] 2017-07-25 17:35
For above ^^ datastreams have the following available titles:
IdentityMD object label:
![screenshot 2017-07-25 10 33 49](https://user-images.githubusercontent.com/796990/28585338-de966a56-7124-11e7-9f24-de97dd0ef5c6.png)
dc:title
![screenshot 2017-07-25 10 34 02](https://user-images.githubusercontent.com/796990/28585341-e29b8a96-7124-11e7-8668-3690cc8ac9e4.png)
MODS:title
![screenshot 2017-07-25 10 34 08](https://user-images.githubusercontent.com/796990/28585346-e6c39cb2-7124-11e7-84bd-d5f135a95290.png)

**Comment by blalbrit** [comment] 2017-07-25 17:36
Once SW index updates with newly released content, I'll update ticket with results there.

**Comment by blalbrit** [comment] 2017-07-25 17:37
In the meantime, to point 3 in the test plan above. Note that dc datastream and public dc have two different values. dc datastream has original title (as identityMD objectLabel):
![screenshot 2017-07-25 10 36 35](https://user-images.githubusercontent.com/796990/28585512-3cdeff2e-7125-11e7-8881-77285ed6453f.png)

**Comment by cbeer** [comment] 2017-07-25 18:05
The collection title on the item page seems unrelated to the original intent of this ticket, does it not?

The public dublin core is mapped from the MODS on-the-fly during publishing and is expected to be different.

**Comment by blalbrit** [comment] 2017-07-25 18:10
@cbeer - yep, just noting something orthogonal to this ticket while gathering information. Can clean it up if that helps - just not sure at this point what is relevant and what isn't at this stage of analysis.

**Comment by blalbrit** [comment] 2017-07-25 18:21
Content now appears in SearchWorks. The problem that prompted this ticket still exists. Please see the following:

1) Collection object in SW with correct title (and filmstrip):
![screenshot 2017-07-25 11 18 26](https://user-images.githubusercontent.com/796990/28587141-feb86716-712a-11e7-8245-46d2ee388c7b.png)

2) Item view in SW with correct collection title:
![screenshot 2017-07-25 11 18 58](https://user-images.githubusercontent.com/796990/28587179-19bad058-712b-11e7-87a3-8d761c03ae2e.png)

3) Search result in SW with the old, incorrect collection title:
![screenshot 2017-07-25 11 19 10](https://user-images.githubusercontent.com/796990/28587201-2bb4c35e-712b-11e7-8e88-590391015b16.png)


As I said before, I'm happy to clean up the above analysis (the item view problems likely belong in some version of https://github.com/sul-dlss/argo/issues/994 ). It is an open question to me whether or not we are supplying bad data to SW, or if SW is handling the collection title the wrong way. @tingulfsen - happy to talk the problem through further with you when you get in.

**Comment by jkeck** [comment] 2017-07-25 18:28
Not sure if this helps at all, but the collection's title on the record view (in the SW UI) comes from the collection object itself (e.g. we make a solr request to fetch the collection object and load the collection information to populate the `In collection` panel).

However; in the search results display we use a field called `collection_with_title` (to prevent us from needing to make redundant solr requests to build the search results view).  So it's possible that all the items need to be re-indexed in order for the correct collection title to show up in the child documents as well.

**Comment by blalbrit** [comment] 2017-07-25 18:31
thanks @jkeck - when you say "all the items need to be re-indexed" do you mean in Argo/DOR, or in SW?

**Comment by blalbrit** [comment] 2017-07-25 18:54
To test @jkeck 's re-index idea above. I have reindexed and two objects have the new collection title associated with them. I have republished the whole set. Expected behavior in the short results would be that two objects have the correct collection_with_title value, and the rest have the old Pirages2017 value. Will check back in a couple of hours to verify.

**Comment by blalbrit** [comment] 2017-07-25 20:43
Reindexing, republishing, and updating release to SW does not seem to impact the title that is being populated in the search results: https://searchworks.stanford.edu/?f%5Bcollection%5D%5B%5D=jv359dd3912&page=2

**Comment by ndushay** [comment] 2017-07-25 23:08
Tommy and I have a lead/theory on what is going on with `jv359dd391` in `SearchWorks`, which is a collection object (thanks @jkeck).  

Tommy is going to see how the field displayed in `Argo` is populated.

@blalbrit is this also an issue for item objects?

**Comment by ndushay** [comment] 2017-07-25 23:10
Tommy and I have a lead/theory on what is going on with `jv359dd391` in `SearchWorks`, which is a collection object (thanks @jkeck).  

Tommy is going to see how the field displayed in `Argo` is populated.

@blalbrit is this also an issue for item objects?

**Comment by blalbrit** [comment] 2017-07-25 23:11
@ndushay - we have had no reports about this for items, just the connection to the collection objects.

**Comment by ndushay** [comment] 2017-07-26 00:36
For SearchWorks, we *think* there is something going on with how `collection_with_title` is populated in sul-dlss/sw-indexer.  it seems to get the title from something it refers to as ?? collection.label ?? 

For Argo, @tingulfsen is investigating where the value for the Collection field is coming from for an Item record view.

**Comment by ndushay** [comment] 2017-07-26 18:44
See sul-dlss/discovery-indexer#32.

**Comment by blalbrit** [comment] 2017-07-26 19:44
Out of scope for Argo work, @ndushay has documented the problem in the appropriate codebase, linked above.

**Closed by blalbrit** 2017-07-26 19:44 UTC
Labels: bug
