### ISSUE TITLE
Argo is not reindexed when when sdr workflow steps run

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#65] opened 2015-11-01 21:27 UTC
Currently, the workflow service sends jms updates to sedora for workflows with 'sdr' as their repository (per Jon Deering). Sedora was a separate, now extinct instance of Fedora originally used by Preservation Core. What we want is a message to the DOR update queue for all workflow updates, no differentiation for repository=sdr vs repository=dor

**Comment by atz** [comment] 2015-11-05 00:40
Is this even an Argo ticket?

**Comment by LynnMcRae** [comment] 2015-11-05 07:18
It's in the sprint because it affects the timeliness and accuracy of the DOR/Argo index which affects Argo users. There may need to be github issues that cover the engineering work itself in another github project of course, linked back to this, but this is how the task gets represented in the sprint?

**Comment by atz** [comment] 2015-11-06 19:05
That's reasonable.  We could also have a cross-project milestone naming convention, but this makes sense.

**Comment by darrenleeweber** [comment] 2015-11-09 23:03
Does anyone know how and where this is configured and/or coded?  A quick search for 'sedora' on the workflow-service project yields no results.

**Comment by LynnMcRae** [comment] 2015-11-10 00:13
Sorry, that text from the original JIRA ticket meant the originally the workflow status update would spawn an update message relevant to the repository associated with the workflow -- repository="dor" would go to a Fedora we call DOR, while repository="sdr" would logically be targeted to the fedora once known as Sedora. The code itself would be about the repository id, not Sedora per se. We only have DOR and the DOR/Argo index now -- the repository distinction proved not useful -- so all workflow messaging should be targeted there.

I'm guess this is the relevant logic in the workflow services framework:

src/edu/stanford/sulair/dlss/dor/service/WorkflowServiceImpl.java 
51	        if(appCtx.containsBean(p.getRepository())){
52	            MessagingService msgService = (MessagingService)appCtx.getBean(p.getRepository() + ".messaging");
53	            msgService.sendObjectUpdatedMessage(p.getDruid());

We could deprecate the "repository" parm/column in the workflow service so the data always says "dor", but that would mean a lot of changes in a lot of places. This might be worth it for a future workflow iteration, if any, that arises from pipeline work. Or have "getRepository" always return "dor"? Seems a setup for unintended consequences. For now workflow services are synonymous with DOR objects, so changing the logic above to always be "dor", with appropriate commentary, seems simplest.

**Comment by darrenleeweber** [comment] 2015-11-10 01:33
Yes, OK.  If the 'repository' distinction is no longer required, then the unique identifier is simply DRUID (right?).

**Comment by darrenleeweber** [comment] 2015-11-10 01:37
Perhaps any methods or RESTful API calls that include the respository parameter could be modified, either to set 'dor' as the default or to remove the parameter.  The latter might require a transition period with deprecation warnings.
I started to look at this because I have SDR experience, but this really has nothing to do with SDR and so I'm assuming @drh-stanford will be assigned to this one.  Ping me if there are implications for the SDR workflow interface (or correct me if I'm assuming too much).

**Comment by drh-stanford** [comment] 2015-11-13 04:45
@LynnMcRae The workflow service has both `dor` and `sdr` repositories in its process state, so it's managing data from both repos. When the message is sent out to our messaging broker, it only includes the druid, not the repo:

  https://github.com/sul-dlss/workflow-service/blob/e3dd3711d19ac1f0a7cd2c506c6e4b3880f25d10/src/edu/stanford/sulair/dlss/dor/service/JmsMessagingService.java#L55

The workflow services has two outgoing messaging pipelines -- one for `dor.messaging` and another for `sdr.messaging`. So, it sounds to me like we might not have a `sdr.messaging` service in our configuration, because Willy has tests for it and the code looks designed to have both sdr and dor messaging pipelines. So I suspect the problem is in the messaging broker/routes. I will take a deeper look.

  https://github.com/sul-dlss/workflow-service/blob/c789b04c92e1a83cfa4eb0818c5e6cb5404396d6/test/edu/stanford/sulair/dlss/dor/service/JmsMessagingServiceTests.java#L87

**Comment by drh-stanford** [comment] 2015-11-13 05:15
It looks to me like messages to `sdr.messaging` get dropped because there isn't an `sdr` bean in the application context like the one for `dor`.

https://github.com/sul-dlss/workflow-service/blob/c789b04c92e1a83cfa4eb0818c5e6cb5404396d6/WebContent/WEB-INF/applicationContext.xml#L49

Willy deleted it last July:

  https://github.com/sul-dlss/workflow-service/commit/7746dec38f8ef063c458057f5eef8861c12f0565

**Comment by drh-stanford** [comment] 2015-11-13 18:36
i see a couple options for fixing this. (a) hardcode all outbound messages to `dor.messaging` or (b) resurrect the `sdr.messaging` pipeline. i think the former is easier and consistent with Lynn's original comment here.

**Comment by drh-stanford** [comment] 2015-11-13 18:45
see PR https://github.com/sul-dlss/workflow-service/pull/8 @atz can you please review this PR?

**Comment by drh-stanford** [comment] 2015-11-20 21:25
the PR is merged and the `workflow-1.20.0.war` is built. next step is to deploy it on -dev

**Comment by drh-stanford** [comment] 2015-11-23 21:13
@LynnMcRae I've been testing my fix and there appears to be some application logic problems. Did the workflow service write to Fedora at one point? That code looks like it's no longer being called and that the WFS does not write to Fedora (and hence isn't sending update messages like it should)...

**Comment by drh-stanford** [comment] 2015-11-23 21:38
See PR https://github.com/sul-dlss/workflow-service/pull/10

**Comment by LynnMcRae** [comment] 2015-11-23 21:39
@drh-stanford when we introduced the workflows datastream to the DOR model, workflow service was auto-upgrading older to add the datastream when it was missing.  I can't say it that was only on the add/initialize workflow call or on status updates as well (the latter would have been a lot of overhead).  Regardless, it would have only influenced indexing if the datastream was missing and had to be added, plus, that all ended sometime in the last couple of years.  DOR's Item Registration service includes the workflows datastream in all objects now. WOrkflow services should have no connection to Fedora except the message sent to motivate reindexing.

**Comment by drh-stanford** [comment] 2015-11-23 22:02
@LynnMcRae ok, that's what I'm seeing in the code -- no connection to Fedora. Thanks.

**Comment by drh-stanford** [comment] 2015-11-25 19:04
This will be fixed when we deploy `workflow-1.20.1.war` into production. I will need to coordinate with devops next week...

**Comment by drh-stanford** [comment] 2015-12-01 22:24
This is now deployed in production. @LynnMcRae you can test it out now.

**Closed by drh-stanford** 2015-12-01 22:24 UTC
Labels: +1, bug
