### ISSUE TITLE
Workflow Step Re-Set Throws Error

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/argo#293] opened 2015-12-03 00:08 UTC
Failed response on workflow step re-set. User workflow was:
1) notice error message
2) enter workflow pop-out
3) try to set workflow step to waiting
4) error response returned

![screenshot 2015-12-02 16 05 20](https://cloud.githubusercontent.com/assets/796990/11548195/dd0d1760-990e-11e5-9028-deed590e694e.png)
![screenshot 2015-12-02 16 05 29](https://cloud.githubusercontent.com/assets/796990/11548200/e21aebec-990e-11e5-823e-aa81965ac22c.png)
![screenshot 2015-12-02 16 05 39](https://cloud.githubusercontent.com/assets/796990/11548205/e629dcfc-990e-11e5-875d-0f0a6348140b.png)

**Comment by drh-stanford** [comment] 2015-12-05 05:26
this might be a duplicate of #220 but the exception message is different in development

**Comment by drh-stanford** [comment] 2015-12-07 21:41
I have a PR that fixes the button itself, but on success it does not put the next workflow view into a modal dialog... like so

![screen shot 2015-12-07 at 1 31 07 pm](https://cloud.githubusercontent.com/assets/1861171/11640574/14be00e8-9ce8-11e5-919f-43d92ba8d4dd.png)

**Closed** 2015-12-10 00:39 UTC
Labels: bug, feature parity
