### ISSUE TITLE
Replace ActiveFedora#Datastream in spec/requests/update_datastream_spec.rb

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/argo#2545] opened 2021-03-21 21:34 UTC

**Comment by jcoyne** [comment] 2021-03-22 15:03
This is a duplicate of #2437/#2535?

**Comment by aaron-collier** [comment] 2021-03-22 20:40
I don't think it's necessarily a duplicate, but is part of them. I won't put this in ready as the PRs that are coming for those tickets will likely close this one.

**Comment by andrewjbtw** [comment] 2021-04-01 18:00
Is this closeable now? The two tickets linked above appear to have been completed.

**Closed** 2021-04-01 20:47 UTC
