### ISSUE TITLE
Form columns are being grouped and/or merged incorrectly when downloading a descriptive metadata spreadsheet via bulk action

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/argo#3782] opened 2022-07-01 20:18 UTC
**Describe the bug**
The bulk action cocina descriptive metadata spreadsheet is grouping the `form` columns in a way that's causing data loss. I updated three items that have DOIs via the spreadsheet and ended up seeing errors related to missing resource types when the DOI update step ran.

I did the following:

1. Download spreadsheet for the three items
2. Add related items to the spreadsheet and make no other changes to what I downloaded
3. Validated the spreadsheet using the bulk action
4. Uploaded the spreadsheet
5. Saw HB alerts related to resource types for all three items:
https://app.honeybadger.io/projects/50568/faults/83331860

I initially thought I made a mistake but then I realized that the bulk action download and the show page download are generating different results for the `form` data. The bulk action seems to be grouping data elements together that belong to separate items in the cocina array.
 
**User Impact**
Users will not be able to make updates to descriptive metadata in bulk without risking accidental modifications. In my case, the incorrect spreadsheet was cocina-valid, so I didn't notice an issue until I saw the error about DataCite. In other cases, the downloaded spreadsheet may not be valid.

**To Reproduce**
1. Go to https://argo.stanford.edu/view/druid:sm043zf7254
2. Download the cocina spreadsheet
3. Go to the bulk actions and choose the spreadsheet download
4. Download the druid again
5. See that the `form` columns are different 

This is the result for the show page download:

form1.source.value | form1.structuredValue1.type | form1.structuredValue1.value | form1.structuredValue2.type | form1.structuredValue2.value | form1.structuredValue3.type | form1.structuredValue3.value | form1.structuredValue4.type | form1.structuredValue4.value | form1.type | form2.source.uri | form2.type | form2.uri | form2.value | form3.source.value | form3.type | form3.value | form4.source.value | form4.type | form4.value | form5.source.code | form5.type | form5.uri | form5.value | form6.source.code | form6.type | form6.value | form7.source.value | form7.type | form7.value
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Stanford self-deposit resource types | type | Mixed Materials | subtype | Data | subtype | Image | subtype | Video | resource type | http://id.loc.gov/vocabulary/resourceTypes/ | resource type | http://id.loc.gov/vocabulary/resourceTypes/dat | Dataset | MODS resource types | resource type | still image | DataCite resource types | resource type | Collection | lcgft | genre | http://id.loc.gov/authorities/genreForms/gf2018026119 | Data sets | local | genre | dataset | MODS resource types | resource type | mixed material

This is the result for the bulk action download:

form1.source.uri | form1.source.value | form1.structuredValue1.type | form1.structuredValue1.value | form1.structuredValue2.type | form1.structuredValue2.value | form1.structuredValue3.type | form1.structuredValue3.value | form1.structuredValue4.type | form1.structuredValue4.value | form1.type | form1.uri | form1.value | form2.source.value | form2.type | form2.value | form3.source.value | form3.type | form3.value | form4.source.value | form4.type | form4.value | form6.source.code | form6.type | form6.uri | form6.value | form7.source.code | form7.type | form7.value
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
http://id.loc.gov/vocabulary/resourceTypes/ | Stanford self-deposit resource types | type | Mixed Materials | subtype | Data | subtype | Image | subtype | Video | resource type | http://id.loc.gov/vocabulary/resourceTypes/dat | Dataset | MODS resource types | resource type | still image | DataCite resource types | resource type | Collection | MODS resource types | resource type | mixed material | lcgft | genre | http://id.loc.gov/authorities/genreForms/gf2018026119 | Data sets | local | genre | dataset

In the bulk action download, the original `form` groupings are not being maintained. I think it may just be an issue of maintaining consistent groupings for `form1`, `form2`, etc. In the bulk action result above, the very first cell with the URI in it seems to be the right header and data but it doesn't belong with "Stanford self-deposit resource types."

I'm attaching both exports I just did to this ticket in case there are even more differences beyond the `form` fields I missed.

Show page download:
[descriptive-sm043zf7254.csv](https://github.com/sul-dlss/argo/files/9031361/descriptive-sm043zf7254.csv)

Bulk action download:
[descriptive-sm043zf7254-bulk.csv](https://github.com/sul-dlss/argo/files/9031362/descriptive-sm043zf7254-bulk.csv)

**Additional info**

I should also add that the item above was one of the ones that got broken and which I then fixed by uploading a corrected spreadsheet. So it's possible I did something wrong when fixing the metadata that makes this not as good of an example as it could be. 

For an example I didn't edit but which had a similar problem when I examined it the same way (by comparing downloads), see: https://argo.stanford.edu/view/dj417rh1007

**Comment by jcoyne** [comment] 2022-07-01 20:33
Is this a duplicate of #3769

**Comment by aaron-collier** [comment] 2022-07-06 17:04
I believe this is now closable, but will defer to @andrewjbtw

**Closed** 2022-07-06 19:28 UTC
Labels: bug, SDR migration carryover
