### ISSUE TITLE
Ops implications for work to be done for Argo to prod updates

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/argo#440] opened 2016-01-12 18:59 UTC
@atz Has been working on updating and enumerating the code that uses dor services https://github.com/sul-dlss/dor-services/issues/136 . Ops needs to be keyed in to what specific updates need to happen (+ ordering) for argo to go to prod.

@sul-dlss/devops

**Comment by mejackreed** [comment] 2016-02-03 22:39
Also related to #490

**Comment by drh-stanford** [comment] 2016-02-12 17:29
duplicate of #490

**Closed by drh-stanford** 2016-02-12 17:29 UTC
Labels: devOps
