### ISSUE TITLE
Detail display, don't die on bad APO or Collection reference

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#334] opened 2015-12-10 00:06 UTC
Objects shouldn't exist with a bad APO or collection reference, but they do, esp with test data. And this is exactly what the UI should show us should it actually happened for real, rather than getting a system error.  In the case of these lookups, show the druid in place of an unresolved lookup, perhaps highlighted somehow (in red?) to signal the problem?

**Comment by mejackreed** [comment] 2015-12-10 00:14
Examples?

**Comment by LynnMcRae** [comment] 2015-12-10 00:20
sorry, this is one of the cases obscured by the generic "Incomplete response received from application".  Apparently my bug report on this condition revealed both a date-interpretation issue and this issue.  DarrenW may have an example ... looking in slack

**Comment by drh-stanford** [comment] 2015-12-10 00:39
There's an example in https://github.com/sul-dlss/argo/issues/293

**Comment by drh-stanford** [comment] 2015-12-18 19:54
To reproduce for an invalid APO:

- Navigate to an item
- Click `identityMetadata`, then `Edit`
- Change the `isGovernedBy` druid to something not found like `druid:aa111bb2222`
- Click Update Datastream

The problem here is that any indexing of the object will now fail because the `to_solr` function no longer works for the object.

So, I believe this fix is substantial as it will involve changing `dor-services` such that it can handle object not found errors in the (potentially many) `to_solr` functions. 

Another possible fix would be to make the `identityMetadata` edit window something that validates that correctness of the XML by checking that the APO and Collection druids are valid.

The workaround is to edit the `identityMetadata` datastream directly from Fedora, which is cumbersome but would work ok.

**Comment by LynnMcRae** [comment] 2015-12-18 21:59
If the to_solr method fails, then we won't be able to index objects in this state at all? This is a more serious situation than being able to find but not display them.  No object should be absent from the Argo index altogether. Do we need to have to_solr catch the error and pass the druid along instead of the expected title in the cases of collection and APO lookups that can't locate the target object?

**Comment by drh-stanford** [comment] 2015-12-18 22:17
@jmartin-sul `to_solr` fails in some cases, like this one where we get ObjectNotFound errors. the reindexing code doesn't handle this case, right? If so, we need to figure out what to do in the case of errors as we won't have the `solr_doc` at the reindex-call level (I marked this issue designNeeded for this reason). See the procedure above for how to get an object into this incorrect state. (Also, might this account for the Solr index being short some objects?)


![screen shot 2015-12-18 at 2 15 09 pm](https://cloud.githubusercontent.com/assets/1861171/11908529/ca07b348-a591-11e5-8e57-c0f2d399e1b5.png)

**Comment by drh-stanford** [comment] 2015-12-18 22:20
btw, I meant `RELS-EXT` not `identityMetadata` in my examples above so I revised them with some screenshots.

**Comment by blalbrit** [comment] 2016-01-21 22:36
@mejackreed - we're triaging tickets. Is this one still active, or - if we have an example to check - is it testable in dev or stage?

**Comment by mejackreed** [comment] 2016-01-21 23:13
I'm not sure if this is still valid or not. Needs further investigation

**Comment by drh-stanford** [comment] 2016-01-22 00:32
it's still an open problem. to reproduce it in -dev or -test, you can use the steps in my Dec 18th comment in this issue (basically hack the item to have a bogus APO).

**Comment by darrenleeweber** [comment] 2016-02-19 16:34
This might have been auto-closed by resolving a PR that tagged it with `fix #334` but there are additional requirements to satisfy for this issue.

**Comment by mejackreed** [comment] 2016-02-19 16:48
@darrenleeweber Could you list those requirements so they can be addressed?

**Comment by darrenleeweber** [comment] 2016-02-19 16:54
The main thing is that it looks like @drh-stanford is working on some aspect of this issue (from the commentary above).  Also, I want to understand how this dovetails with the APO PR.

**Comment by darrenleeweber** [comment] 2016-02-19 22:00
I've now resolved my concerns about conflicting specs in commits today on
https://github.com/sul-dlss/argo/pull/532

If we get that merged and deployed, the QA should sign off on this issue.

**Comment by atz** [comment] 2016-02-26 23:35
Consensus in the room here is that this is accomplished within the scope of this ticket (and w/ corresponding fix in dor-services).  Closing.

**Closed by atz** 2016-02-26 23:35 UTC
Labels: blocker, bug
