### ISSUE TITLE
Register/edit APO - Bad default license data created

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/argo#70] opened 2015-11-01 22:09 UTC
Choosing a public domain mark resulted in this in the defaultObjectRights: 

```
<use> 
    <human type="useAndReproduction"/> 
    <human type="creativeCommons">Public Domain Mark 1.0</human> 
    <human type="openDataCommons"/> 
    <machine type="openDataCommons" uri="https://creativecommons.org/publicdomain/mark/1.0/">pdm</machine> 
  </use> 
```
The second `<human>` statement should be "openDataCommons" and the third, empty one should not be there.

**Comment by drh-stanford** [comment] 2015-11-03 00:14
The `pdm` mark is coded up as a creative commons license, not a open data commons license -- see here:

  https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/models/editable.rb#L37

If that assumption is correct, then it looks to me like the correct XML would be:

```
<use>
  <human type="useAndReproduction"/>
  <human type="creativeCommons">Public Domain Mark 1.0</human> 
  <machine type="creativeCommons" uri="https://creativecommons.org/publicdomain/mark/1.0/">pdm</machine>
</use>
```

**Comment by LynnMcRae** [comment] 2015-11-03 00:47
You are correct, both human and machine should be creativeCommons for pdm.

Though not a part of this ticket per se, note that the empty \<human type="useAndReproduction"/> is also bad and should be omitted.

**Comment by drh-stanford** [comment] 2015-11-03 21:34
Ok, so Argo should generate the following `use` XML in `defaultObjectRights` when `pdm` is selected during APO registration:

```
<use>
  <human type="creativeCommons">Public Domain Mark 1.0</human> 
  <machine type="creativeCommons" uri="https://creativecommons.org/publicdomain/mark/1.0/">pdm</machine>
</use>
```

**Comment by LynnMcRae** [comment] 2015-11-03 22:06
This looks good, +1 on adding the uri. I now remember a discussion of using the URI to capture the version of the license in play.

Conferred with Rob on preferences for URIs used.  Please remove the /legalcode or /us/legalcode from the end of the other creative commons license references.

**Comment by drh-stanford** [comment] 2015-11-03 22:59
I haven't been successful in locating the source of the error. It appears that it's in `dor-services' defaultObjectRights` datastream -- in the way the terminology is defined. But I don't have a way to test it in my current laptop configuration.

See https://github.com/sul-dlss/dor-services/blob/develop/lib/dor/datastreams/default_object_rights_ds.rb#L14

So, I think I need to pair with someone to fix this...

**Comment by drh-stanford** [comment] 2015-11-06 00:19
I paired with Joe and was successful in getting a partial fix here: https://github.com/sul-dlss/dor-services/pull/110

The next fix is to purge the empty XML elements:

```
  <use>
    <human type="useAndReproduction"/>
    <human type="creativeCommons">Public Domain Mark 1.0</human>
    <machine type="creativeCommons" uri="https://creativecommons.org/publicdomain/mark/1.0/">pdm</machine>
    <human type="openDataCommons"/>
    <machine type="openDataCommons" uri=""/>
  </use>
```

to

```
  <use>
    <human type="creativeCommons">Public Domain Mark 1.0</human>
    <machine type="creativeCommons" uri="https://creativecommons.org/publicdomain/mark/1.0/">pdm</machine>
  </use>
```

**Comment by LynnMcRae** [comment] 2015-11-06 01:11
Check with Tommy on the MODS XML cleaning he does for spreadsheet input. It's 99% about eliminating empty tags, attributes, and containers with a final xmllint for formatting. It was meant to be applicable to all incoming XML.

**Comment by drh-stanford** [comment] 2015-11-13 04:26
@tingulfsen can you point me to the XML cleanup code?

**Comment by drh-stanford** [comment] 2015-11-14 17:58
The cleanup code is in the modsulator gem as per #71

**Comment by drh-stanford** [comment] 2015-11-19 23:37
met with @tingulfsen and will update the normalization code to the revised modsulater when its ready

**Comment by drh-stanford** [comment] 2015-11-20 18:50
i'm going to close this issue as it is now a duplicate of #71 . the core issue here is fixed and will be deployed when we upgrade Argo to the latest version of dor-services.

**Closed by drh-stanford** 2015-11-20 18:50 UTC
Labels: bug, feature parity
